### ISSUE TITLE
Changing Pixels Per Second giving weird results on Canvas

### ISSUE THREAD

**Issue by Tragio** [bbc/waveform-data.js#106]
Hello 👋 

Thank you very much for the amazing work and for making this open-source. I'm developing a web application that uses both waveform and waveform-data.js. 😄 

Since the audio files are around 2 hours long I reduce the pixels per second to 1 so I can have smaller .json files.

`audiowaveform -i file.mp3 -o file.json --pixels-per-second 1 -b 8`

This is the result:
<img width="741" alt="CleanShot 2022-04-04 at 09 37 55@2x" src="https://user-images.githubusercontent.com/5109593/161507782-3be5dd6a-ed71-4eac-87f0-a93674811666.png">

Then I tried to change it to 2 but still gave some weird lines:
![CleanShot 2022-04-04 at 09 39 00@2x](https://user-images.githubusercontent.com/5109593/161507853-6706f4b8-1798-4950-b5af-4c3a60298afc.png)

Finally, I tried to use 3, and looks better but interesting enough it's not aligned with the div and the size of the .json increased to 150kb.
![CleanShot 2022-04-04 at 09 41 26@2x](https://user-images.githubusercontent.com/5109593/161508101-72b8f1c9-4913-4f63-a63f-b2baefb9f2a5.png)
 
At this point, I'm not sure if is the library or some funky thing I'm doing in canvas. Here is the code:

```js
    fetch(this.music.waveform)
        .then((response) => response.json())
        .then((json) => WaveformData.create(json))
        .then((waveform) => {
          const canvas = document.getElementById('wave-full')
          const channel = waveform.channel(0)
          canvas.width = waveform.length

          const scaleY = (amplitude, height) => {
            const range = 150
            return height - (amplitude * height) / range
          }

          const ctx = canvas.getContext('2d')
          ctx.beginPath()

          // Drawing the waveform
          for (let x = 0; x < waveform.length; x++) {
            const val = channel.max_sample(x)
            ctx.lineTo(x, scaleY(val, canvas.height))
          }

          ctx.closePath()
          ctx.fillStyle = 'rgba(51,51,51,0.4)'
          ctx.strokeStyle = 'transparent'
          ctx.stroke()
          ctx.fill()
        })
```

Thank you very much for the help 🙏

**Comment by chrisn** [comment]
This looks to be an issue with the way you're drawing on the canvas rather with than the JSON files. You're drawing the waveform as a filled path, so maybe try setting the start/end points to the zero position, e.g:

```js
ctx.moveTo(0, scaleY(0, canvas.height));

for (let x = 0; x < waveform.length; x++) {
  const val = channel.max_sample(x)
  ctx.lineTo(x, scaleY(val, canvas.height))
}

ctx.lineTo(waveform.length, scaleY(0, canvas.height));
```

**Comment by Tragio** [comment]
@chrisn you're awesome, it worked. Thank you very much ❤️
