### ISSUE TITLE
retour automatique du curseur au début

### ISSUE THREAD

**Issue by NinaP48** [bbc/waveform-data.js#114]
Bonjour, j'essaie de reproduire une forme d'onde en utilisant wave-form data. Le code que j'ai utilisée est exactement celui de l'exemple : https://waveform.prototyping.bbc.co.uk/
Cependant quand je clique sur ma forme d'onde mon curseur retourne automatiquement au début. Ce phénomène est-il provoqué par quelque chose en particulier ?

**Comment by chrisn** [comment]
Are you using Peaks.js? It could relate to this issue: https://github.com/bbc/peaks.js/issues/233#issuecomment-441192973

**Comment by NinaP48** [comment]
j'utiliser un serveur http python

**Comment by chrisn** [comment]
I know that `python -mhttp.server` will not work, as it does not support HTTP byte-range requests. Have you tried [rangehttpserver](https://pypi.org/project/rangehttpserver/)?

**Comment by thom4parisot** [comment]
Un peu de doc (en anglais) sur [l'entête `Range`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests), qui doit être comprise par le serveur HTTP sinon il ne renvoie pas les données attendues par Peaks/Waveform.

**Comment by NinaP48** [comment]
En effet, cela a l'air de fonctionner avec le Range HTTP Server. Merci beaucoup !
