### ISSUE TITLE
Create 16 bit samples with Javascript API

### ISSUE THREAD

**Issue by jameadows** [bbc/waveform-data.js#119]
With the command line utility I can generate 16 bit samples that render smooth looking waveforms.  AFAICT the Javascript API is hardcoded to 8 bit  (by setting a '1' into location 4 of the header) and these render grainy waveforms.  Short of changing the code is there an API to enable 16 bit samples, and is there a specific reason why it's fixed to 8 bits?

Thanks in advance, this is a really handy module!

**Comment by chrisn** [comment]
Thanks! It is possible to use 16-bit waveform files from `audiowaveform`, but it looks like `WaveformData.createFromAudio()` only produces 8-bit data - is that the API method you want to use?

**Comment by jameadows** [comment]
Thanks for your speedy reply!  Yes, I'd like to generate 16 bit data using createFromAudio().  I've taken a closer look at the code in generateWaveform and see that it assumes 8 bit throughout.  So I guess there's no magic config option :)  

I'll try changing generateWaveform to handle 8 or 16 bit and if I'll send a PR in case you're interested.  Thanks again.

**Comment by chrisn** [comment]
Sorry, you're the first to need this, so it was never implemented. You're very welcome to send a PR - thank you!

**Comment by jameadows** [comment]
I posted a PR.  Thanks and cheers!

**Comment by jameadows** [comment]
Issue is resolved, thanks for your help.

**Comment by chrisn** [comment]
Thank you! If it's OK I'd prefer to rename the new option as `bits`, as I tend to think of bits per sample rather than bytes. I'll make the change and release a new version to npm soon.

**Comment by chrisn** [comment]
This is now available in v4.5.0 via npm. Thanks again!
