### ISSUE TITLE
.min and .max performs expensive calculations

### ISSUE THREAD

**Issue by cjohansen** [bbc/waveform-data.js#27]
I just debugged a performance issue after moving from `.forEach` to a regular `for` loop to draw my waveform. Now, I would agree that the iterator methods are better most of the time, but still, I was very baffled to find that this change made my rendering ~50x slower. The reason is that `data.min` is a computed property, and it computes on _every access_. I would not expect waveform-data to make any calculations outside calls to `resample`, so I would suggest the `min` and `max` properties either be calculated when resampling, or at least be made lazy, so that they only ever compute once.

**Comment by oncletom** [comment]
@cjohansen oh nice finding. How do you use waveform-data? I never faced that because I usually cache `.min` in another scoped variable.

ES2015 iterators could be a nice option too :-)

**Comment by cjohansen** [comment]
Here's my current drawing function:

```js
  ctx.beginPath();

  for (var x = 0, l = min.length; x < l; x += 4) {
    ctx.lineTo(x, origo);

    var minY = y(min[x]);
    ctx.lineTo(x, minY);
    ctx.lineTo(x + 2, minY);
    ctx.lineTo(x + 2, origo);

    var maxY = y(max[x]);
    ctx.lineTo(x + 2, maxY);
    ctx.lineTo(x + 4, maxY);
    ctx.lineTo(x + 4, origo);
  }

  ctx.closePath();
```

It basically draws the waveform as a line diagram, much like Sound cloud's waveforms. If you change `min` to `data.min`, performance drops 50x. There are of course many ways around this, but nonetheless, this cost me an hour or so of debugging this morning. Optimizing property access really is a last measure in my book, and the current behavior is not really expected.

I guess the easiest fix is to calculate lazily. You could also re-calculate whenever data changes, but that would mean changing in at least two places: `resample` and `offset`, possibly others as well.

**Comment by oncletom** [comment]
Thanks for the additional details. You are right that without an explicit variable caching, it is easy to get a performance hit by blindly trusting `.min` and `.max`.

I have not dug yet into this level of optimisation (lazy evaluation). I thought of memoizing the min/max and clearing it after offset/resampling, as you mentioned. If you have other optimisation patterns/lazy array evaluation resources, I would be happy to read them and to implement the most appropriate one.

Thanks :-)

**Comment by oncletom** [comment]
Note for self: it also applies to `segment`.

**Comment by cjohansen** [comment]
> I have not dug yet into this level of optimisation (lazy evaluation). I thought of memoizing the min/max and clearing it after offset/resampling, as you mentioned. If you have other optimisation patterns/lazy array evaluation resources, I would be happy to read them and to implement the most appropriate one.

That was pretty much what I had in mind. An alternate approach would be to only calculate new values in the constructor, but then you need to make sure no methods mutate the waveform data. From my (limited) experience with waveform-data, that means that `offset` should return a new object rather than modifying the existing one, like `resample` does. But that would be a breaking change. If that's a no-go, your suggestion sounds fine.

**Comment by oncletom** [comment]
An immutable waveform-data instance would require more work but it is good idea on the long term — I discovered the joy of immutability after having shipped waveform-data ;-)

So step 1 is memoizing (w/ `lodash.memoize`) and step 2 is immutability.

Thanks again, both for raising the issue and for your work (which is used in this project as of `sinon.js` :-D)

**Comment by cjohansen** [comment]
Sounds great! :) :beer:

**Comment by chrisn** [comment]
waveform-data.js v3.0 has `min_sample(index)` and `max_sample(index)` methods that return values directly, rather than arrays. If you actually need an array, you can use `min_array()` and `max_array()`.
