### ISSUE TITLE
"can generate waveform data using the Web Audio API."

### ISSUE THREAD

**Issue by TrySpace** [bbc/waveform-data.js#30]
I'm only seeing examples to generate waves through `raw_data` which is `.json` or `.dat`.

But there are no examples of how to generate a `wavedata.json` through a direct link to either `mp3` or `wav`. This should be possible right?

**Comment by oncletom** [comment]
Hello @TrySpace,

yes this is indeed doable directly from a mp3/ogg/wav as long as your browser has the codec to decode the data. There is an example in the source code:

```js
var xhr = new XMLHttpRequest();

// URL of a CORS MP3/Ogg file
xhr.open("GET", "http://example.com/audio/track.ogg");
xhr.responseType = "arraybuffer";

xhr.addEventListener("load", function onResponse(progressEvent){
  WaveformData.builders.webaudio(this.response, onProcessed(waveform){
    console.log(waveform.duration);
  });
});

xhr.send();
```

**Comment by oncletom** [comment]
Hello @TrySpace, as of `waveform-data@2.0.0`, the README documents the [WebAudio waveform data generator](https://github.com/bbc/waveform-data.js#using-web-audio).

Have fun :-)
