### ISSUE TITLE
Can I use waveform-data with bytearray audio data ?

### ISSUE THREAD

**Issue by boatdheeraj** [bbc/waveform-data.js#35]
Can I use waveform-data to create waveform from raw pcm audio data in bytearray format ? I have to deal with 16-bit signed PCM to create waveform on web page and I am looking for an API that can support this audio data format. After reading waveform-data js in github I cannot find the answer for using this API with bytearray audio data, so I decide to ask you directly.

**Comment by oncletom** [comment]
@boatdheeraj are you talking about doing so in the browser? If so, you can use the now documented [Web Audio builder](https://github.com/bbc/waveform-data.js#using-web-audio) to do so.

On the Node.js side of things, you would need to use a JavaScript codec to decode your data, pass them to the [lib/builder/audiodecoder.js](https://github.com/bbc/waveform-data.js/blob/master/lib/builders/audiodecoder.js) function to get a waveform-data instance out of it.

**Comment by davidturissini** [comment]
In the browser, you’ll need to decode the array buffer first. Then you can use the decoded audio buffer

**Comment by chrisn** [comment]
You can create waveform data directly from an `ArrayBuffer` using the `WaveformData.createFromAudio()` method, see the [API documentation](https://github.com/bbc/waveform-data.js/blob/master/doc/API.md#waveformDatacreatefromaudiooptions-callback).
