### ISSUE TITLE
would it be possible to stream audio data?

### ISSUE THREAD

**Issue by mreinstein** [bbc/waveform-data.js#41]
All of the examples I've seen operate on a complete buffer of data. What I'd like to do is generate a visualization of a waveform as it's being recorded in the browser.

Is this possible with waveform-data.js?

thanks for a great project by the way!

**Comment by chrisn** [comment]
Thanks! That's not currently possible, but would be a welcome addition!

**Comment by mreinstein** [comment]
while this would be nice to have I suspect it might be difficult to shoe-horn this into `waveform-data` because there are no streaming constructs. I've found this module, which provides a simplistic way to stream audio data into a waveform in both node and the browser: 

https://github.com/audio-lab/waveform
