### ISSUE TITLE
Can not do a function waveform

### ISSUE THREAD

**Issue by aahedi** [bbc/waveform-data.js#44]
Is it can do a function like this:

if waveform is low then hide image, else show image.

repeating function on when playing audio

Example:
![audio-waveform](https://user-images.githubusercontent.com/8935884/27990809-dc8eaa56-648c-11e7-9ca2-4ac6823e51b5.png)

**Comment by chrisn** [comment]
Hello, and sorry it's taken such a long time to reply.

It should be possible to do what you want, using waveform-data.js:
- During playback, either use a `timeupdate` event or poll the `currentTime` property of the `<audio>` element to get the current playback time
- Convert the playback time to pixels using `const index = waveformData.at_time(currentTime)`
- Get the waveform amplitude at the index using `const min = waveformData.min_sample(index)` and `const max = waveformData.max_sample(index)`
- Check if `min` and `max` are above some threshold, and show or hide the image as appropriate.

I hope this helps!
