### ISSUE TITLE
Create adaptor for MediaStreams

### ISSUE THREAD

**Issue by davidturissini** [bbc/waveform-data.js#46]
## Problem
Currently, waveform-data only supports rendering waveforms for audio files that have a known length. I would like to use this library to render waveforms from WebRTC MediaStreams.

## Proposal
I propose that a new Adapter type be created that is backed by a ScriptProcessor node (https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode). This would unlock rendering MediaStream waveforms, and, as a side effect, allow arbitrary combinations of AudioNodes to be rendered as well.

## Caveats
Because of the nature of Media Streams vs Audio files, it is necessary to update or introduce API changes to allow for async activity. This represents a major change in existing waveform api, where it is currently possible to get min and max values via `waveform.min` and `waveform.max` calls. This change will require some sort of callback pattern, and I think that the Observable pattern is a good fit for this.

This change would also require that `onAudioDecoded` (https://github.com/bbc/waveform-data.js/blob/master/lib/builders/audiodecoder.js#L39) be broken down to return a `DataView` instead of a Waveform object.

This kind of adapter is also different from current adapters because there needs to be a way to tell the adapter to `start` and `stop` collecting data for its internal AudioBuffer.

## Code
Here is my first pass implementation of a ScriptProcessorNode. Note that some of this code uses libraries that are available in my application at large, and I certainly wouldn't advocate using them in a real implementation. This is just to get the conversation started.

```
class ScriptProcessorAdapter {
    constructor(audioContext, processor) {
        this.audioContext = audioContext;
        this.processor = processor;
        this.buffer = audioContext.createBuffer(2, 1, audioContext.sampleRate);
        this.data = normalize(this.buffer);
    }

    start() {
        return Observable.create((o) => { //RXJS flavor observables
            const onAudioProcess = (evt) => {
                // get the processor node's input
                const { inputBuffer } = evt;
                const { length:start, audioContext, buffer } = this; // cache length
                 // We need to concat the new inputBuffer with what we already have
                this.buffer = concatenateAudioBuffers(audioContext, buffer, inputBuffer);
                // normalize this to DataView. `normalize` is a broken out version of `onAudioDecoded`
                this.data = normalize(this.buffer);
                o.next();
            }
            this.processor.addEventListener('audioprocess', onAudioProcess);

            return () => {
                this.processor.removeEventListener('audioprocess', onAudioProcess);
            }
        })
    }

    at(index) {
        return Math.round(this.data.getInt8(20 + index));
    }

    get length() {
        return this.data.getUint32(16, true);
    }

    fromResponseData(responseData) {
        return this;
    }
}
```

## Usage:
```
const adapter = new ScriptProcessorAdapter(audioContext, scriptProcessor);
const waveform = new WaveformData(scriptProcessor, adapter);

// Elsewhere
const subscription = adapter.start()
  .subscribe(() => {
        // This line is a bit awkward because we have to tell the waveform that new data
        //  is present, and it needs to rebuild its min/max arrays
        this.waveform.offset(0, this.adapter.length);
        // render to canvas
        this.draw(this.waveform);
  });


// Elsewhere again
subscription.unsubscribe();
```

**Comment by davidturissini** [comment]
Closing this. A better approach is to make a custom Web Audio API node that generates a waveform. That covers this case.

**Comment by chrisn** [comment]
@davidturissini Apologies for not responding to this much earlier. We'd like to include such a node in the library. Live stream visualisation is a use case that would be great to support.

**Comment by davidturissini** [comment]
@chrisn I have something. Let me clean it up a bit. I'll open a PR in a few days. In the meantime, I think Live stream is better tracked in this issue: https://github.com/bbc/waveform-data.js/issues/62
