### ISSUE TITLE
Outdated documentation?

### ISSUE THREAD

**Issue by ffxsam** [bbc/waveform-data.js#51]
The README shows this example:

```js
xhr.addEventListener('load', (progressEvent) => {
  WaveformData.builders.webaudio(audioContext, progressEvent.target.response, (err, waveform) => {
    if (err) {
      console.error(err);
      return;
    }

    console.log(waveform.duration);
  });
});
```

But `WaveformData.builders` is undefined. I'm importing it like so:

```js
import WaveformData from 'waveform-data';
```

**Comment by ffxsam** [comment]
@oncletom No problem! I figured it out quite easily, just wanted to point it out.

**Comment by oncletom** [comment]
I see. I'm going to open a PR to fix this inaccuracy. Thanks for reporting it 🙂

**Comment by ffxsam** [comment]
Sounds good. And a million thanks for this repo, it's saved me many hours of time and headaches!
