### ISSUE TITLE
Create waveform from audioArray

### ISSUE THREAD

**Issue by floydback** [bbc/waveform-data.js#53]
My WebAudioApi based player already decoded audio data (from arrayBuffer to audioBuffer). How to build waveform from **audioBuffer**? This https://github.com/bbc/waveform-data.js#with-fetch help only to build waveform from arrayBuffer

ps I can't decode audioArray twice because of error
`Cannot decode detached ArrayBuffer`

**Comment by juliancode** [comment]
when will this get pushed to npm?
