### ISSUE TITLE
Deprecate point, segment, and offset methods

### ISSUE THREAD

**Issue by chrisn** [bbc/waveform-data.js#58]
I'm currently working on #56, to add support for multi-channel waveforms, and as part of this I am reviewing all API methods provided by waveform-data.js.

There are a number of methods that are unused in [Peaks.js](https://github.com/bbc/peaks.js) and [elsewhere](https://www.npmjs.com/browse/depended/waveform-data):

* `.offset()`, `.offset_start`, `.offset_end`, `.offset_length`, and `.offset_duration`
* `.segments` and `.set_segment()`
* `.points`, `.set_point()`, and `.remove_point()`

As multi-channel support will be a breaking API change, I am considering also removing the above methods at the same time. But, I don't want to break existing applications, so if you are using any of these methods, please leave a comment to let me know.

**Comment by oncletom** [comment]
Hm 🤔 I think `offset` was used in BBC Redux (Peaks was never implemented in the UI, I think), to "clamp" the view on a certain beginning and end; it helped build zoom levels manually.

segment and points were an attempt to prepare their implementation in Peaks, but they were implemented only in Peaks. I'm pretty sure these ones are good to go and if they exist, they should extensions of this module, and not part of the core.

**Comment by chrisn** [comment]
These are now removed in v3.0.0.
