### ISSUE TITLE
Supported way of accessing WaveformDataArrayBufferAdapter's DataView?

### ISSUE THREAD

**Issue by jdelStrother** [bbc/waveform-data.js#64]
In v2 we used to be able to read the underlying ArrayBuffer from a WaveformData instance with `waveform.adapter.data.buffer`.  In v3 we can still technically do it (`waveform._adapter._data.buffer`) but that doesn't seem ideal.

Would you be opposed to adding a public accessor for the DataView?

**Comment by chrisn** [comment]
Why do you need access to the DataView? (Note that if you're using JSON format waveform data, then there is no DataView.) I'd prefer to have a public API that supports developer needs, without requiring knowledge of the underlying data representation.

**Comment by jdelStrother** [comment]
I have a sequence consisting of pieces of audio (each as an ArrayBuffer), and I'm resampling each in turn using waveform-data's audiodecoder.  Once they've all been resampled, I get the underlying dataviews and concatenate them into one long WaveformData instance, which is later passed to peaks.js.

I totally concede this is very hacky & probably niche use case.

**Comment by chrisn** [comment]
I see, so we could possibly add a method to append one WaveformData instance to another, e.g., `WaveformData.append(waveformData)`. Would that work?

**Comment by jdelStrother** [comment]
Yep, sounds good.  Shall I try & come up with a PR?

**Comment by chrisn** [comment]
That'd be great, please do!

**Comment by oncletom** [comment]
Love the `.append()`!

**Comment by jdelStrother** [comment]
Do you have a preference whether append mutates the receiver, or returns a new instance?

**Comment by chrisn** [comment]
I agree with returning a new instance, but suggest the name `.concat()` (as per the `Array` method) since to me `.append()` would imply mutation.

**Comment by chrisn** [comment]
A new release, v3.1.0 is now published on npm. Thanks for your contribution!
