### ISSUE TITLE
Angular issues upgrading from 3.1.0 to 3.3.1

### ISSUE THREAD

**Issue by klanglie** [bbc/waveform-data.js#68]
I am using the latest version of Angular 9 at the time of this writing. It is an Angular-CLI project. When I upgrade and try to serve the project, I am greeted with the following errors after upgrade:

ERROR in node_modules/waveform-data/waveform-data.d.ts:46:4 - error TS1036: Statements are not allowed in ambient contexts.

46   };
      ~
node_modules/waveform-data/waveform-data.d.ts:194:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

194   export = WaveformData;

**Comment by chrisn** [comment]
Thanks for reporting this. I have just published v3.3.2, which should fix these problems.

To get waveform-data.js working in an Angular app, I had to add this to `polyfills.ts`:

```ts
(window as any).global = window;
```
