### ISSUE TITLE
Doesn't work in Chrome<=40 starting from v3.0.0

### ISSUE THREAD

**Issue by Dantist** [bbc/waveform-data.js#73]
Hi!

Starting from `v3.0.0` this package doesn't work in Chrome<=40 (despite it in the supported browsers list).

The failing line is: 
https://github.com/bbc/waveform-data.js/blob/master/lib/adapters/arraybuffer.js#L32

And the error message is: 
```
SyntaxError : Use of const in strict mode [arraybuffer.js:32]
```

**Comment by chrisn** [comment]
Thanks for reporting this. The supported browsers list isn't up to date (and hasn't been updated in years, see [here](https://ci.testling.com/bbcrd/waveform-data.js)). I've raised this as issue #74. If you need support for older browsers, we can limit use of newer language features (i.e., replace `const` with `var` in this case).

**Comment by Dantist** [comment]
Yeah, I have replaced `const` and `let` with `var` in several places and it is working fine on older Chrome. This is a pretty easy fix, so maybe it is better to fix this and not to bump the supported browsers versions :-)

I saw that CI was not run for years, so I was guided by this list: https://github.com/bbc/waveform-data.js#browser-support

**Comment by chrisn** [comment]
Would you like to send a PR with your fixes?
