### ISSUE TITLE
Get frequency data for a specific time window in a WebAudio context?

### ISSUE THREAD

**Issue by larrywal** [bbc/waveform-data.js#79]
In my app I allow the user to upload a file; I use peaks.js to show a waveform using webAudio and allow the user to play the file.

For my application, I also want to be able to allow the user to visualize beats for specific frequencies.  E.g. I'll have a light pulsing with the beat of the lowest third frequencies, one pulsing with the mid range frequencies, and one for high.

I see WebAudio let's me create an analyser but I don't think it lets me specify a start and duration to return frequency data for.  I could use Wavesurfer to export PCM data, but I haven't found a library to process it.

Could waveform-data help me?  And/or any suggestions?  There is so much code floating around doing beat analysis, PCM export, and analyzing using WebAudio, I think it's just a matter of connecting the dots.....

**Comment by chrisn** [comment]
Sorry, I can't help with this, it's outside the scope of waveform-data.js.  If you can find or write a library that takes an AudioBuffer and locates the beat positions, you could possibly use Peaks.js point markers to trigger the lights.

**Comment by larrywal** [comment]
@chrisn Got it - appreciate the response - last (dumb, I think) question....is there a way to get the AudioBuffer from peaks.js since I'm already using that to load the file on the page and I'd prefer not to load it twice...

**Comment by chrisn** [comment]
Yes, you may find this demo useful: https://github.com/bbc/peaks.js/blob/master/demo/external-player.html. See also https://github.com/bbc/peaks.js/blob/master/customizing.md#media-playback

**Comment by larrywal** [comment]
Thank you so much.
