### ISSUE TITLE
Disabling web worker

### ISSUE THREAD

**Issue by Christilut** [bbc/waveform-data.js#81]
Is there a way to disable the web worker and just run the process in the current thread?
I'm running a batch analysis in a thread pool with Threads.js and this already creates a web worker for each task. Running the web worker inside the web worker causes problems during compile of Threads and running a web worker inside a web worker is not very efficient either.

**Comment by chrisn** [comment]
A PR would be welcome to make the worker optional.

**Comment by Christilut** [comment]
I created a PR: #82 

I found out afterwards that the WebAudio API is not available inside web workers though, which means my use case ended there. I wanted to both resample and create waveforms in bulk in web workers, the resampling is not possible through OfflineAudioContext inside the worker.

I'll probably use the C++ version instead. Feel free to deny the PR if you feel that it doesn't benefit anyone.

**Comment by Christilut** [comment]
Also what I noticed was that this library supports IE9 but web workers are not available in IE9 so I think IE9 hasn't been supported since the InlineWorker addition? I could be mistaken though.
For obvious reasons I can't really test it in IE9 ;)
