### ISSUE TITLE
D3.js example not working

### ISSUE THREAD

**Issue by GonzaloGPF** [bbc/waveform-data.js#85]
Hi,
I'm trying to visualize D3 example from readme, however, I'm no able to make it work.
I'm new to D3 and do not understand how I can render a waveform using that example. I think its outdated and there are variables/methods that doesnt exists.
I'd like to draw a waveform using D3 so I modified example with this, but its rendering absolutelly in screen, without scaling.
```
    const channel = waveform.channel(0);
    const offsetX = 100;
    const min = channel.min_array();
    const max = channel.max_array();

    const svg = d3.select('#waveform-container')
        .append('svg')
        .attr("width", 100)
        .attr("height", 100)
        .attr('viewBox', '-5 -20 35 40');

    const x = d3.scaleLinear()
        .domain([0, waveform.length])
        .rangeRound([0, 1024]);

    const y = d3.scaleLinear()
        .domain([d3.min(min), d3.max(max)])
        .rangeRound([offsetX, -offsetX]);
            
    const area = d3.area()
        .x((d, i) => x(i))
        .y0((d, i) => y(min[i]))
        .y1((d, i) => y(d));

    svg.select('path')
        .datum(max)
        .attr('transform', () => `translate(0, ${offsetX})`)
        .attr('d', area);
```
Plz help, how could I draw waveform that adapts to container's width?
Thanks!

**Comment by chrisn** [comment]
I'm sorry that the example didn't work, I have now fixed this, and also added a demo page at demo/d3.js.

**Comment by GonzaloGPF** [comment]
A lot of thanks!
Now its working perfectly!
